2019-02-15 16:25:04,864 ERROR: Exception on /search [GET] [in /Users/youns/Documents/Vuno/flask_tutorial/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/youns/Documents/Vuno/flask_tutorial/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/youns/Documents/Vuno/flask_tutorial/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/youns/Documents/Vuno/flask_tutorial/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/youns/Documents/Vuno/flask_tutorial/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/youns/Documents/Vuno/flask_tutorial/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/youns/Documents/Vuno/flask_tutorial/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/youns/Documents/Vuno/flask_tutorial/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/youns/Documents/Vuno/flask_tutorial/app/main/routes.py", line 142, in search
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POST_PER_PAGE'])
KeyError: 'POST_PER_PAGE'
2019-02-15 16:25:41,265 INFO: Microblog startup [in /Users/youns/Documents/Vuno/flask_tutorial/app/__init__.py:78]
